---
- name: Provision and Configure Instance
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create EC2 Instance using Terraform
      shell: terraform apply -auto-approve
      args:
        chdir: /your/path/to/workingDir
      register: terraform_apply_output
      changed_when: false

    - name: Retrieve Terraform Output
      shell: terraform output instance_public_ip
      args:
        chdir: /your/path/to/workingDir
      register: terraform_output

    - name: Set dynamic host for the created instance
      set_fact:
        instance_ip: "{{ terraform_output.stdout | regex_replace('\"', '') }}"
    
    - name: Display the command output
      debug:
        var: instance_ip


- name: Configure Instance
  hosts: localhost
  gather_facts: false

  vars:
    private_key_path: "your_private_key_file"

  tasks:
    - name: Include dynamic inventory
      include_vars:
        file: hosts.yaml
        name: inventory

    - name: Add instance to dynamic inventory
      add_host:
        name: "newHost"
        ansible_host: "{{ instance_ip }}"
        ansible_ssh_private_key_file: "{{ private_key_path }}"
        ansible_user: ubuntu  # Adjust the SSH username if needed
        ansible_connection: ssh
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"


- name: Install Packages on Instance
  hosts: newHost
  gather_facts: false
  #become: true
  become_user: ubuntu

  tasks:
    - name: Update apt
      shell: sudo apt update
      args:
        chdir: /home/ubuntu
    
    - name: Install java
      shell: sudo apt install -y openjdk-17-jdk openjdk-17-jre
      args:
        chdir: /home/ubuntu
    
    - name: Transferring scripts
      copy:
        src: scripts/
        dest: /home/ubuntu
        mode: 0755
    
    - name: move all scripts to respective place
      shell: 
        cmd: sudo chmod u+x starting
        cmd: sudo mv starting eula.sh /opt/minecraft/server/
      args:
        chdir: /home/ubuntu
    
    - name: move service
      shell: 
        cmd: sudo mv mineFinal.service /etc/systemd/system/
      args:
        chdir: /home/ubuntu
    
    - name: Running eula.sh and starting service
      shell: sudo bash eula.sh
      args:
        chdir: /opt/minecraft/server
        
